### PR TITLE
Upgrade log4j to v2.16.0

### LINKED ISSUE #123: Upgrade log4j to v2.16.0
We recently upgraded to log4j v2.15.0. However, it is recommended to update to 2.16.0 ASAP.

https://archive.apache.org/dist/logging/log4j/2.16.0/apache-log4j-2.16.0-bin.zip

infrastructure/issues/6302#issuecomment-38708769

### PR DESCRIPTION
**Pull request by Mesbah-Alam**
Resolves https://github.com/adoptium/STF/issues/123

Signed-off-by: Mesbah-Alam <Mesbah_Alam@ca.ibm.com>

### CODE REVIEW

**Comment by Mesbah-Alam** [comment]
Test : Grinder/20024

**Comment by Mesbah-Alam** [comment]
Note: Will have to manually trigger all instances of the systemtest.getDependency job at all Jenkins instances after delivering this PR.

**Review by llxia — APPROVED** [review]
Thanks @Mesbah-Alam

**Comment by llxia** [comment]
https://openj9-jenkins.osuosl.org/job/systemtest.getDependency/13

**Comment by llxia** [comment]
https://ci.adoptopenjdk.net/job/systemtest.getDependency/163/

**Comment by Mesbah-Alam** [comment]
Thanks for running the systemtest.getDependency jobs, @llxia !

**Pull request merged**
