### PR TITLE
Add BSD support

### PR DESCRIPTION
**Pull request by battleblow**
* Use gmake on *BSD as well as on AIX.
* Teach get-platform-prefix about *BSD.

### CODE REVIEW

**Comment by battleblow** [comment]
Added an additional commit to stfUtility.pm.  Previous commits got us past the set up phase of system testing.  Now I'm working on getting them to actually run.

**Comment by battleblow** [comment]
With the last set of changes to PlatformFinder the system tests now run on FreeBSD.

**Comment by battleblow** [comment]
Any questions from the reviewers or anything I can do to help move forward here?

Similarly for https://github.com/AdoptOpenJDK/stf/pull/67

**Review by smlambert — APPROVED** [review]
LGTM - some other BSD related changes in other repos still pending, along with needing a machine at the project to actually be able to verify these changes work, but do not need to wait for them to merge this one.

**Comment by smlambert** [comment]
related: https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/291

**Pull request merged**
