### PR TITLE
Revert "update ant 1.10.1 to 1.10.2 version"

### PR DESCRIPTION
**Pull request by Mesbah-Alam**
Reverts AdoptOpenJDK/stf#32

### CODE REVIEW

**Review by sxa — CHANGES_REQUESTED** [review]
I don't think this should be committed until there is a change to pull 1.10.1 from the correct location ready as this is a breaking change in isolation.

**Comment by Mesbah-Alam** [comment]
@sxa555 Do you propose we update this PR and include the correct path to Ant 1.10.1 in this PR itself?

**Comment by Mesbah-Alam** [comment]
Instead of 'reverting' the previous change, I will simply create a fresh PR in which I'd manually revert 1.10.2->1.10.1 and update the path for download

**Comment by Mesbah-Alam** [comment]
Alternative PR created : https://github.com/AdoptOpenJDK/stf/pull/34

**Pull request closed without merging**
