### PR TITLE
Update to support v12+

### PR DESCRIPTION
**Pull request by smlambert**
add isJavaVersion(int) method

### CODE REVIEW

**Comment by smlambert** [comment]
I have specifically chosen not to delete the isJavaX() methods, as they are public, and some are called in systemtest material, found in openjdk-systemtest repo.  Those can and should be removed/replaced with isJavaVersion(int) in a separate PR.  Definitely can use a clean-up...

./openjdk.test.debugging/src/test.debugging/net/adoptopenjdk/stf/jdi/JdiTest.java:		if (jvm.isIBMJvm() && jvm.isJava8()) {
Shelleys-MacBook-Pro:openjdk-systemtest slambert$ grep -r 'getJavaVersion' .
./openjdk.test.load/src/test.load/net/adoptopenjdk/stf/MauveSingleThreadLoadTest.java:		if (jvm.getJavaVersion() >= 9) { 
./openjdk.test.load/src/test.load/net/adoptopenjdk/stf/MauveMultiThreadLoadTest.java:		if (jvm.getJavaVersion() >= 9) { 
./openjdk.test.load/src/test.load/net/adoptopenjdk/stf/MauveSingleInvocationLoadTest.java:		if (jvm.getJavaVersion() >= 9) { 
./openjdk.test.load/src/test.load/net/adoptopenjdk/stf/ClassloadingLoadTest.java:		int javaVersion = test.env().primaryJvm().getJavaVersion();

This also assumes that javaVersionOutput normalizes to 'openjdk version "XX', which also covers the case 'openjdk version "XX-internal'.  If that were to change in future versions, this will again have to be updated.

**Comment by smlambert** [comment]
Keeping as WIP, until some grinders are run.

**Review by llxia — APPROVED** [review]
LGTM

**Comment by smlambert** [comment]
Grinders for jdk12:
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder_Sandbox/127/
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder_Sandbox/128/
Grinders for jdk8, jdk11 (openj9, hotspot):
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1035/
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1034
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1036/
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1037/

**Pull request merged**
