### PR TITLE
Fix procdump

### PR DESCRIPTION
**Pull request by lumpfish**

### CODE REVIEW

**Comment by lumpfish** [comment]
sanity.system test runs are in
jdk8
openj9
x86-64_windows: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4541/ (two test failures but unrelated to this change)
jdk11
hotspot
x86-64_windows: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4542/

**Comment by lumpfish** [comment]
Fixes https://github.com/AdoptOpenJDK/stf/issues/86

**Comment by Mesbah-Alam** [comment]
Could we please squash the commits into a single commit?

**Comment by Mesbah-Alam** [comment]
The PR looks good. 

The Grinders above didn't really run the code added in this PR. It'd be conclusive to see a test where we have a "hang" and the procdump tool gets invoked successfully. 

Running a simple [grinder](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4569/console) with the original failing test didn't give us the original "hang", as it's an intermittent issue. 

So, I added a target for `SampleOverrunProcess` and ran it in [grinder](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4573/consoleFull), and I do see the dump being created in the resultant zip. 

Output from 1.CL.jvmdump.stdout: 

```
[11:01:08] Dump 1 initiated: E:\workspace\Grinder\openjdk-tests\TKG\test_output_1604595588538\SampleOverrunProcess_0\20201105-105950-SampleOverrunProcess\results\java.exe_201105_110108.dmp
[11:01:08] Dump 1 writing: Estimated dump file size is 114 MB.
[11:01:08] Dump 1 complete: 114 MB written in 0.2 seconds
[11:01:08] Dump count reached.
``` 

I am not sure what exact Perl version (32 bit or 64 bit) was used in the build. It says: 

"This is perl 5, version 30, subversion 3 (v5.30.3) built for x86_64-cygwin-threads-multi".

**Comment by lumpfish** [comment]
I would imagine 32 bit perl would say "built for x86_32-cygwin-threads-multi", and it would be included in a 32 bit cygwin installation.
In my local testing I used Strawberry perl (native Windows version of perl).
Presumably the use of 32 bit will diminish over time.  Strawberry perl are still building a 32 bit version: http://strawberryperl.com/releases.html.

**Comment by lumpfish** [comment]
No reason not to squash.  Using github's "Squash and merge" is easiest.

**Review by Mesbah-Alam — APPROVED** [review]
LGTM

**Pull request merged**
