### PR TITLE
Upgrade to log4j v2.15.0

### LINKED ISSUE #121: Upgrade log4j to 2.15.0
For system tests, we are using log4j version 2.13.3
https://github.com/adoptium/STF/blob/6abbb82d569585e2c2a1f62bf7aedfdfc4594730/stf.build/include/top.xml#L51

We need to upgrade it to the latest version (2.15.0) due to security issues. See infrastructure/issues/6302

### PR DESCRIPTION
**Pull request by llxia**
Resolves: https://github.com/adoptium/STF/issues/121
Signed-off-by: lanxia <lan_xia@ca.ibm.com>

### CODE REVIEW

**Review by karianna — APPROVED** [review]
LGTM

**Comment by llxia** [comment]
Internal 
- sanity.system: Grinder/19980 passed
- extended.system Grinder/19981 passed

**Review by smlambert — APPROVED** [review]
thanks @llxia !

**Comment by llxia** [comment]
`systemtest.getDependency` job on all Jenkins needs to be triggered after this PR to ensure we pre-stage upgraded log4j.

**Comment by llxia** [comment]
https://openj9-jenkins.osuosl.org/job/systemtest.getDependency/12/
```
configure-log4j:
     [echo] Executing macro download-file
     [echo] File to download: https://archive.apache.org/dist/logging/log4j/2.15.0/apache-log4j-2.15.0-bin.zip
```

**Comment by smlambert** [comment]
https://ci.adoptopenjdk.net/view/all/job/systemtest.getDependency/152 - done

**Comment by Mesbah-Alam** [comment]
Thanks for taking care of this, @llxia !

**Pull request merged**
