### PR TITLE
Add logic to handle multiple /.. at the end of path

### PR DESCRIPTION
**Pull request by Mesbah-Alam**
Resolves https://github.com/AdoptOpenJDK/stf/issues/58
Signed-off-by: Mesbah_Alam@ca.ibm.com <Mesbah_Alam@ca.ibm.com>

### CODE REVIEW

**Comment by Mesbah-Alam** [comment]
Tested with: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder-systemtest/87/console

**Comment by Mesbah-Alam** [comment]
Reviewer: @sophia-guo

**Comment by sophia-guo** [comment]
Reading the code and comments only file names end with "/.."  will be reconstructed to  "// Make file names more readable by converting '/x/y/..' to '/x' " 
https://github.com/AdoptOpenJDK/stf/blob/00e8e525b0b0a3912071ef701df9ded3877a4c22/stf.core/src/stf.core/net/adoptopenjdk/stf/environment/DirectoryRef.java#L60
https://github.com/AdoptOpenJDK/stf/blob/00e8e525b0b0a3912071ef701df9ded3877a4c22/stf.core/src/stf.core/net/adoptopenjdk/stf/environment/DirectoryRef.java#L61.
If we do have some files name like `PERF_ROOT=/home/jenkins/workspace/Grinder-systemtest/../../benchmarks` the name wont be reconstructed. 

The main function of the block `if (this.fileName.endsWith("/..")) {}` is to threw exception if path is wrong. https://github.com/AdoptOpenJDK/stf/blob/00e8e525b0b0a3912071ef701df9ded3877a4c22/stf.core/src/stf.core/net/adoptopenjdk/stf/environment/DirectoryRef.java#L65
I would suggestion to delete all reconstructed code and keep the path as is. 

Something like:

```
		if (this.fileName.endsWith("/..")) {
			//Throw an exception if we're attempting to go "up" the path from root.
			if( this.fileName.equals("/..") || this.fileName.substring(1).equals(":/..") ) {
								throw new StfException("Directory " + this.fileName	+ " does not have a parent directory,"
								+ " so " + this.fileName + "/.. will not work. Setting to " + this.fileName);
			}
		}

```

**Comment by Mesbah-Alam** [comment]
@lumpfish - do you agree with Sophia's suggestion above to get rid of all the logic for "Making file names more readable by converting '/x/y/..' to '/x' where possible." ? 

I have provided a fix in this PR to handle cases like "/x/y/z/.../..". However, it is also true that, this code does not "make file names more readable" when we have paths such as "/x/../y". 

Are there any other places in STF where the existing logic is used? If not, it may be a simpler thing to not even try to go up steps when we see "/.." at the trailing end of paths.

**Comment by lumpfish** [comment]
Since java7 there has been java.nio.file.Path and java.nio.file.Paths.  The normalize method can be used to resolve all "." and ".." path references - e.g.
```
import java.nio.file.Path;
import java.nio.file.Paths;

public class ResolvePath {
	public static void main(String[] args) {
		String unresolvedFileName = "/a/b/../../c/d/e/f/../../a.txt";
		Path p1 = Paths.get(unresolvedFileName);
		System.out.println("p1 = " + p1);
		Path p2 = p1.normalize();
		System.out.println("p2 = " + p2);
	}
}
```
STF doesn't currently use it because it can currently be built with java6, but we could just move up to java7 being the prereq level.

**Comment by Mesbah-Alam** [comment]
I don't think we are testing Java 6 anywhere with STF based tests. So moving prereqs up to Java 7 should be possible. However, I guess the main question here is whether or not we need to bother about normalizing paths at all-- and the answer seems to be that it's a "nice to have" thing, given we can remove all ".." in the paths. 

I'll refresh the PR with use of ` java.nio.file.Path and java.nio.file.Paths` APIs.

**Comment by Mesbah-Alam** [comment]
PR has been refreshed with use of Path APIs. 

Tested: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder-systemtest/89/

@sophia-guo : could you please review?

**Review by sophia-guo — APPROVED** [review]

**Comment by lumpfish** [comment]
If we're going with java.nio.file.Path we should be able to remove all the stf code which deals paths containing "/..".  The only thing to consider is whether we need to convert the path back to forward slashes on Windows after the normalize().

**Comment by sophia-guo** [comment]
Approved. @Mesbah-Alam The build: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder-systemtest/89/ can't prove the it fixes the issue https://github.com/AdoptOpenJDK/openjdk-tests/pull/1043 . Please also launch a grinder with this change and https://github.com/AdoptOpenJDK/openjdk-tests/pull/1043 against jdk8 before merge.

**Comment by Mesbah-Alam** [comment]
> If we're going with java.nio.file.Path we should be able to remove all the stf code which deals paths containing "/.."

Here are the reasons why I kept the existing STF code for 2 cases: 

1) "Throw an exception if we're attempting to go "up" the path from root", i.e. --  if( this.fileName.equals("/..") || this.fileName.substring(1).equals(":/..") ) { we are throwing an exception}. However, using Path API, if fileName == "/..", it will return "/". 

2) "If it's a relative directory, we can't be sure if it does/does not exist until we're ready to check if it exists, so ignore the ..'s.", i.e.-- this.fileName.startsWith("./..") {return;}. However, in this case the Path API may return an empty string -- which does not help. 

Hence, keeping those two if blocks before using the Path API seems a safer option.

**Comment by Mesbah-Alam** [comment]
@sophia-guo : this PR only pertains to https://github.com/AdoptOpenJDK/stf/issues/58

https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder-systemtest/89/rebuild/parameterized - was launched with the changes for https://github.com/AdoptOpenJDK/openjdk-tests/pull/1043 

Note, `ADOPTOPENJDK_BRANCH = removeJAVA_HOME_from_systemtest_playlists`

I'll launch a full test build (e..g sanity.system, extended.system) for https://github.com/AdoptOpenJDK/openjdk-tests/pull/1043 afterwords ofcourse.

**Comment by lumpfish** [comment]
Agreed, this will get over the immediate issue.  Perhaps we could see whether the code code be slimmed down via a future PR.  normalize() doesn't actually depend on a resource existing - it just manipulates the string, I believe.

**Review by lumpfish — APPROVED** [review]

**Pull request merged**
