### PR TITLE
Add RISC-V support to the STF framework

### PR DESCRIPTION
**Pull request by ChengJin01**
Signed-off-by: Cheng Jin <jincheng@ca.ibm.com>

### CODE REVIEW

**Comment by ChengJin01** [comment]
Reviewer: @Mesbah-Alam, @llxia 
FYI: @smlambert

**Comment by Mesbah-Alam** [comment]
@ChengJin01 - could you please add a Grinder link with a test that executes these changes?

**Comment by ChengJin01** [comment]
@Mesbah-Alam,  the changes were verified on the hardware. We expect the tests to be executed in the emulator (or hardware if available) after finishing the setup for the test automation at lab. So there is no way to run Grinder with these changes for the moment.

**Comment by Mesbah-Alam** [comment]
@ChengJin01 - correct, I forgot that this is RISC and there is no way we can run grinders. Besides, I see that you posted your testing output in the related internal issue. That's enough. Thanks.

**Comment by Mesbah-Alam** [comment]
@ChengJin01 - Could you please run a Grinder with a single System test target (e.g. ClassLoadingTest) on a Linux platform, using your STF branch for this PR and also your [System test branch ](https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/381/files) ? This will confirm these changes will not break system test builds.

**Comment by ChengJin01** [comment]
@Mesbah-Alam,  Grinder with all changes in stf & systemtests has been created at https://ci.adoptopenjdk.net/job/Grinder/4978/ to see how it goes.

**Review by Mesbah-Alam — APPROVED** [review]
LGTM

**Comment by ChengJin01** [comment]
The grinder at https://ci.adoptopenjdk.net/job/Grinder/4978/ passed without any error.

**Pull request merged**
