### PR TITLE
Fix IBM java detection

### PR DESCRIPTION
**Pull request by ben-walsh**
Signed-off-by: Ben Walsh <ben_walsh@uk.ibm.com>

### CODE REVIEW

**Review by smlambert — COMMENTED** [review]
Should check where this method is used, and if there is a need for an isOpenJ9() method or not, as this file only contains isIBMJvm or isOracleJvm

**Comment by Mesbah-Alam** [comment]
Why exactly do we need to make this change? 

If we remove `javaVersionOutput.contains("OpenJ9")` check from `isIBMJvm()`, then tests that use this method (e.g. JdiTest, HCRLateAttachWorkload, JCK etc) will fail to run on OpenJ9 SDKs. 

I suggest if we do remove this check from isIBMJvm(), we add a new method like: 

```
public boolean isOpenJ9Jvm() throws StfException {
		return (javaVersionOutput.contains("OpenJ9"));
	}
```

And then update the tests where isIBMJvm() is used, and replace that calls with calls to isOpenJ9Jvm().

Also, 
1) We need to add a new method in StfEnvironment equivalent to `verifyUsingIBMJava()` (e.g. verifyUsingOpenJ9Java()) - and update references accordingly.
2) We need to add a new method in JavaVersion equivalent to `verifyUsingIBMJava()` (e.g. verifyUsingOpenJ9Java() - and update references accordingly.

**Comment by karianna** [comment]
@ben-walsh & @Mesbah-Alam - Should we close off this PR?

**Comment by smlambert** [comment]
I will close this.  If we need it, we can raise a fresh PR.

**Pull request closed without merging**
